version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  localstack:
    image: localstack/localstack:stable
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - EDGE_PORT=4566
    ports:
      - "4566:4566"